"""add_person_id_indexes

Revision ID: 016583969152
Revises: 03e66235b593
Create Date: 2026-01-21 05:33:03.616074

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '016583969152'
down_revision: Union[str, Sequence[str], None] = '03e66235b593'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.create_index('ix_record_person_id', ['person_id'], unique=False)

    with op.batch_alter_table('attendance_sessions', schema=None) as batch_op:
        batch_op.create_index('ix_session_person_date', ['person_id', 'date'], unique=False)
        batch_op.create_index('ix_session_person_id', ['person_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_session_person_id')
        batch_op.drop_index('ix_session_person_date')

    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.drop_index('ix_record_person_id')

    # ### end Alembic commands ###
