"""unify_face_database_and_add_sync_columns

Revision ID: 23a22e45e7a1
Revises: 4f83b1692d41
Create Date: 2026-02-01 10:38:58.242868

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "23a22e45e7a1"
down_revision: Union[str, Sequence[str], None] = "4f83b1692d41"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "faces",
        sa.Column("person_id", sa.String(), nullable=False),
        sa.Column("embedding", sa.LargeBinary(), nullable=False),
        sa.Column("embedding_dimension", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("organization_id", sa.String(), nullable=True),
        sa.Column("cloud_id", sa.String(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "last_modified_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("person_id"),
    )
    with op.batch_alter_table("faces", schema=None) as batch_op:
        batch_op.create_index("ix_face_person_id", ["person_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_faces_cloud_id"), ["cloud_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_faces_organization_id"), ["organization_id"], unique=False
        )

    with op.batch_alter_table("attendance_groups", schema=None) as batch_op:
        batch_op.add_column(sa.Column("cloud_id", sa.String(), nullable=True))
        batch_op.add_column(
            sa.Column("version", sa.Integer(), server_default="1", nullable=False)
        )
        batch_op.add_column(
            sa.Column(
                "last_modified_at",
                sa.DateTime(),
                server_default=sa.text("(CURRENT_TIMESTAMP)"),
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column("is_deleted", sa.Boolean(), server_default="0", nullable=False)
        )
        batch_op.create_index(
            batch_op.f("ix_attendance_groups_cloud_id"), ["cloud_id"], unique=False
        )

    with op.batch_alter_table("attendance_members", schema=None) as batch_op:
        batch_op.add_column(sa.Column("cloud_id", sa.String(), nullable=True))
        batch_op.add_column(
            sa.Column("version", sa.Integer(), server_default="1", nullable=False)
        )
        batch_op.add_column(
            sa.Column(
                "last_modified_at",
                sa.DateTime(),
                server_default=sa.text("(CURRENT_TIMESTAMP)"),
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column("is_deleted", sa.Boolean(), server_default="0", nullable=False)
        )
        batch_op.create_index(
            batch_op.f("ix_attendance_members_cloud_id"), ["cloud_id"], unique=False
        )

    with op.batch_alter_table("attendance_records", schema=None) as batch_op:
        batch_op.add_column(sa.Column("cloud_id", sa.String(), nullable=True))
        batch_op.add_column(
            sa.Column("version", sa.Integer(), server_default="1", nullable=False)
        )
        batch_op.add_column(
            sa.Column(
                "last_modified_at",
                sa.DateTime(),
                server_default=sa.text("(CURRENT_TIMESTAMP)"),
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column("is_deleted", sa.Boolean(), server_default="0", nullable=False)
        )
        batch_op.create_index(
            batch_op.f("ix_attendance_records_cloud_id"), ["cloud_id"], unique=False
        )

    with op.batch_alter_table("attendance_sessions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("cloud_id", sa.String(), nullable=True))
        batch_op.add_column(
            sa.Column("version", sa.Integer(), server_default="1", nullable=False)
        )
        batch_op.add_column(
            sa.Column(
                "last_modified_at",
                sa.DateTime(),
                server_default=sa.text("(CURRENT_TIMESTAMP)"),
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column("is_deleted", sa.Boolean(), server_default="0", nullable=False)
        )
        batch_op.create_index(
            batch_op.f("ix_attendance_sessions_cloud_id"), ["cloud_id"], unique=False
        )

    with op.batch_alter_table("attendance_settings", schema=None) as batch_op:
        batch_op.add_column(sa.Column("cloud_id", sa.String(), nullable=True))
        batch_op.add_column(
            sa.Column("version", sa.Integer(), server_default="1", nullable=False)
        )
        batch_op.add_column(
            sa.Column(
                "last_modified_at",
                sa.DateTime(),
                server_default=sa.text("(CURRENT_TIMESTAMP)"),
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column("is_deleted", sa.Boolean(), server_default="0", nullable=False)
        )
        batch_op.create_index(
            batch_op.f("ix_attendance_settings_cloud_id"), ["cloud_id"], unique=False
        )
        batch_op.drop_column("updated_at")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("attendance_settings", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "updated_at",
                sa.DATETIME(),
                server_default=sa.text("(CURRENT_TIMESTAMP)"),
                nullable=False,
            )
        )
        batch_op.drop_index(batch_op.f("ix_attendance_settings_cloud_id"))
        batch_op.drop_column("is_deleted")
        batch_op.drop_column("last_modified_at")
        batch_op.drop_column("version")
        batch_op.drop_column("cloud_id")

    with op.batch_alter_table("attendance_sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_attendance_sessions_cloud_id"))
        batch_op.drop_column("is_deleted")
        batch_op.drop_column("last_modified_at")
        batch_op.drop_column("version")
        batch_op.drop_column("cloud_id")

    with op.batch_alter_table("attendance_records", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_attendance_records_cloud_id"))
        batch_op.drop_column("is_deleted")
        batch_op.drop_column("last_modified_at")
        batch_op.drop_column("version")
        batch_op.drop_column("cloud_id")

    with op.batch_alter_table("attendance_members", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_attendance_members_cloud_id"))
        batch_op.drop_column("is_deleted")
        batch_op.drop_column("last_modified_at")
        batch_op.drop_column("version")
        batch_op.drop_column("cloud_id")

    with op.batch_alter_table("attendance_groups", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_attendance_groups_cloud_id"))
        batch_op.drop_column("is_deleted")
        batch_op.drop_column("last_modified_at")
        batch_op.drop_column("version")
        batch_op.drop_column("cloud_id")

    with op.batch_alter_table("faces", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_faces_organization_id"))
        batch_op.drop_index(batch_op.f("ix_faces_cloud_id"))
        batch_op.drop_index("ix_face_person_id")

    op.drop_table("faces")
    # ### end Alembic commands ###
