"""add hash column to face

Revision ID: 85a8db237b9d
Revises: 23a22e45e7a1
Create Date: 2026-02-01 10:57:10.401882

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "85a8db237b9d"
down_revision: Union[str, Sequence[str], None] = "23a22e45e7a1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("faces", schema=None) as batch_op:
        batch_op.add_column(sa.Column("hash", sa.String(), nullable=True))
        batch_op.create_index(batch_op.f("ix_faces_hash"), ["hash"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("faces", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_faces_hash"))
        batch_op.drop_column("hash")

    # ### end Alembic commands ###
