name: Contributors

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  contributors:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: akhilmhdh/contributors-readme-action@v2.3
        with:
          use_username: true
          columns_per_row: 8
          image_size: 80
          committer_username: github-actions[bot]
          committer_email: 41898282+github-actions[bot]@users.noreply.github.com
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
